import AppKit
import Foundation

@MainActor
final class SettingsStore: ObservableObject {
    static let shared = SettingsStore()

    private enum Key {
        static let policies = "itemPolicies.v1"
        static let bundlePolicies = "bundlePolicies.v1"
        static let knownItems = "knownItems.v1"
        static let windowBindings = "windowBindings.v1"
        static let monitorEnabled = "continuousMonitorEnabled"
        static let expanded = "hiddenSectionExpanded"
        static let language = Localization.languageDefaultsKey
        static let appearance = "appearanceMode"
        static let showInDock = "showInDock"
        static let externalDisplayMode = "externalDisplayMode.v1"
        static let aiInstallationID = "aiInstallationID.v1"
        static let aiLastRecommendationDate = "aiLastRecommendationDate.v1"
        static let aiRecommendationDates = "aiRecommendationDates.v1"
        // v2 drops descriptions generated by the former OneDrive-pinning prompt.
        static let aiItemDescriptions = "aiItemDescriptions.v2"
    }

    @Published var policies: [String: ItemDisposition] {
        didSet { persistPolicies() }
    }

    @Published var bundlePolicies: [String: ItemDisposition] {
        didSet { persistBundlePolicies() }
    }

    @Published var knownItems: [String: KnownMenuBarItem] {
        didSet { persistKnownItems() }
    }

    private(set) var windowBindings: [String: PersistedWindowBinding] {
        didSet { persistWindowBindings() }
    }

    @Published var continuousMonitorEnabled: Bool {
        didSet { defaults.set(continuousMonitorEnabled, forKey: Key.monitorEnabled) }
    }

    @Published var isExpanded: Bool {
        didSet { defaults.set(isExpanded, forKey: Key.expanded) }
    }

    @Published var language: AppLanguage {
        didSet { defaults.set(language.rawValue, forKey: Key.language) }
    }

    @Published var appearanceMode: AppearanceMode {
        didSet { defaults.set(appearanceMode.rawValue, forKey: Key.appearance) }
    }

    @Published var showInDock: Bool {
        didSet { defaults.set(showInDock, forKey: Key.showInDock) }
    }

    @Published var externalDisplayMode: ExternalDisplayMode {
        didSet { defaults.set(externalDisplayMode.rawValue, forKey: Key.externalDisplayMode) }
    }

    let aiInstallationID: String

    @Published private(set) var aiRecommendationDates: [Date] {
        didSet {
            guard let data = try? JSONEncoder().encode(aiRecommendationDates) else { return }
            defaults.set(data, forKey: Key.aiRecommendationDates)
        }
    }

    @Published private(set) var aiItemDescriptions: [String: [String: String]] {
        didSet { persistAIItemDescriptions() }
    }

    private let defaults = UserDefaults.standard

    private init() {
        let loadedPolicies: [String: ItemDisposition]
        if
            let data = defaults.data(forKey: Key.policies),
            let decoded = try? JSONDecoder().decode([String: ItemDisposition].self, from: data)
        {
            loadedPolicies = decoded.filter { !Self.isAnonymousStableID($0.key) }
        } else {
            loadedPolicies = [:]
        }
        policies = loadedPolicies

        let loadedKnownItems: [String: KnownMenuBarItem]
        if
            let data = defaults.data(forKey: Key.knownItems),
            let decoded = try? JSONDecoder().decode([String: KnownMenuBarItem].self, from: data)
        {
            loadedKnownItems = Self.sanitizedKnownItems(decoded)
        } else {
            loadedKnownItems = [:]
        }
        knownItems = loadedKnownItems

        if
            let data = defaults.data(forKey: Key.bundlePolicies),
            let decoded = try? JSONDecoder().decode([String: ItemDisposition].self, from: data)
        {
            bundlePolicies = decoded
        } else {
            // Migrate existing per-item choices into a stable app-level
            // fallback so a changing status-item identity keeps its policy.
            var migrated = [String: ItemDisposition]()
            for known in loadedKnownItems.values.sorted(by: { $0.lastSeen < $1.lastSeen }) {
                if let disposition = loadedPolicies[known.id], !known.semanticBundleIdentifier.isEmpty {
                    migrated[known.semanticBundleIdentifier] = disposition
                }
            }
            bundlePolicies = migrated
        }

        if
            let data = defaults.data(forKey: Key.windowBindings),
            let decoded = try? JSONDecoder().decode([String: PersistedWindowBinding].self, from: data)
        {
            windowBindings = decoded.filter { Self.isUsableBinding($0.value) }
        } else {
            windowBindings = [:]
        }

        continuousMonitorEnabled = defaults.object(forKey: Key.monitorEnabled) as? Bool ?? true
        isExpanded = defaults.object(forKey: Key.expanded) as? Bool ?? true
        language = AppLanguage(rawValue: defaults.string(forKey: Key.language) ?? "") ?? .english
        appearanceMode = AppearanceMode(rawValue: defaults.string(forKey: Key.appearance) ?? "") ?? .system
        showInDock = defaults.object(forKey: Key.showInDock) as? Bool ?? false
        externalDisplayMode = ExternalDisplayMode(
            rawValue: defaults.string(forKey: Key.externalDisplayMode) ?? ""
        ) ?? .showAll
        if let storedID = defaults.string(forKey: Key.aiInstallationID), !storedID.isEmpty {
            aiInstallationID = storedID
        } else {
            let generatedID = UUID().uuidString.lowercased()
            aiInstallationID = generatedID
            defaults.set(generatedID, forKey: Key.aiInstallationID)
        }
        if
            let data = defaults.data(forKey: Key.aiRecommendationDates),
            let decoded = try? JSONDecoder().decode([Date].self, from: data)
        {
            aiRecommendationDates = decoded
        } else if let legacyDate = defaults.object(forKey: Key.aiLastRecommendationDate) as? Date {
            aiRecommendationDates = [legacyDate]
        } else {
            aiRecommendationDates = []
        }
        if
            let data = defaults.data(forKey: Key.aiItemDescriptions),
            let decoded = try? JSONDecoder().decode([String: [String: String]].self, from: data)
        {
            aiItemDescriptions = decoded
        } else {
            aiItemDescriptions = [:]
        }

        // Persist the sanitized values so invalid identities from pre-0.1.3
        // builds cannot return on the next launch.
        persistPolicies()
        persistBundlePolicies()
        persistKnownItems()
        persistWindowBindings()
    }

    func disposition(for item: MenuBarItem) -> ItemDisposition {
        if PlatformVersion.isMacOS27OrNewer {
            return bundlePolicies[item.semanticBundleIdentifier]
                ?? policies[item.id]
                ?? .visible
        }
        return policies[item.id]
            ?? bundlePolicies[item.semanticBundleIdentifier]
            ?? .visible
    }

    func hasPolicy(for item: MenuBarItem) -> Bool {
        policies[item.id] != nil
            || bundlePolicies[item.semanticBundleIdentifier] != nil
    }

    func disposition(forBundleIdentifier bundleIdentifier: String) -> ItemDisposition {
        bundlePolicies[bundleIdentifier] ?? .visible
    }

    func setDisposition(_ disposition: ItemDisposition, for item: MenuBarItem) {
        policies[item.id] = disposition
        if !item.semanticBundleIdentifier.isEmpty {
            bundlePolicies[item.semanticBundleIdentifier] = disposition
        }
    }

    func aiDescription(for id: String, language: AppLanguage) -> String? {
        aiItemDescriptions[language.rawValue]?[id]
    }

    func setAIDescriptions(_ descriptions: [String: String], language: AppLanguage) {
        guard !descriptions.isEmpty else { return }
        var localizedDescriptions = aiItemDescriptions[language.rawValue] ?? [:]
        localizedDescriptions.merge(descriptions) { _, new in new }
        aiItemDescriptions[language.rawValue] = localizedDescriptions
    }

    func recordAIRecommendation(at date: Date = .now) {
        aiRecommendationDates = aiRecommendationDates.filter {
            Calendar.current.isDate($0, inSameDayAs: date)
        } + [date]
    }

    func applyAppearance() {
        NSApp.appearance = appearanceMode.appearance
    }

    func remember(_ items: [MenuBarItem]) {
        var updated = knownItems
        var updatedBindings = windowBindings
        let seenAt = Date.now
        var rememberedBundles = Set<String>()
        for item in items where
            !item.isProtected
            && !item.isAnonymousControlCenterItem
            && !item.hasUnknownHostIdentity
        {
            if PlatformVersion.isMacOS27OrNewer {
                guard rememberedBundles.insert(item.semanticBundleIdentifier).inserted else { continue }
                // Visibility is app-scoped on macOS 27. Replace stale AX
                // identities so one app cannot accumulate duplicate history.
                updated = updated.filter {
                    $0.value.semanticBundleIdentifier != item.semanticBundleIdentifier
                        || $0.key == item.id
                }
            }
            let candidate = KnownMenuBarItem(
                id: item.id,
                displayName: item.displayName,
                detail: item.detail,
                symbolName: item.symbolName,
                semanticBundleIdentifier: item.semanticBundleIdentifier,
                semanticIdentifier: item.semanticIdentifier,
                lastSeen: seenAt
            )
            // A five-second discovery timer must not rewrite UserDefaults and
            // invalidate the whole settings UI on every pass. Refresh recency
            // occasionally, but persist identity/metadata changes immediately.
            if let existing = updated[item.id],
               existing.displayName == candidate.displayName,
               existing.detail == candidate.detail,
               existing.symbolName == candidate.symbolName,
               existing.semanticBundleIdentifier == candidate.semanticBundleIdentifier,
               existing.semanticIdentifier == candidate.semanticIdentifier,
               seenAt.timeIntervalSince(existing.lastSeen) < 600
            {
                // Nothing meaningful changed.
            } else {
                updated[item.id] = candidate
            }
            updatedBindings = updatedBindings.filter {
                $0.value.stableID != item.id || $0.key == String(item.windowID)
            }
            updatedBindings[String(item.windowID)] = PersistedWindowBinding(
                stableID: item.id,
                displayName: item.displayName,
                symbolName: item.symbolName,
                semanticBundleIdentifier: item.semanticBundleIdentifier,
                semanticIdentifier: item.semanticIdentifier,
                rawTitle: item.rawTitle,
                isProtected: item.isProtected
            )
        }
        if updated != knownItems { knownItems = updated }
        if updatedBindings != windowBindings { windowBindings = updatedBindings }
    }

    func restoredItems(from windows: [RawStatusWindow]) -> [MenuBarItem] {
        windows.compactMap { window in
            guard let binding = windowBindings[String(window.windowID)] else { return nil }
            return MenuBarItem(
                id: binding.stableID,
                windowID: window.windowID,
                hostPID: window.hostPID,
                hostBundleIdentifier: window.hostBundleIdentifier,
                semanticBundleIdentifier: binding.semanticBundleIdentifier,
                semanticIdentifier: binding.semanticIdentifier,
                rawTitle: binding.rawTitle,
                displayName: binding.displayName,
                symbolName: binding.symbolName,
                frame: window.frame,
                isProtected: binding.isProtected
            )
        }
    }

    private func persistPolicies() {
        guard let data = try? JSONEncoder().encode(policies) else { return }
        defaults.set(data, forKey: Key.policies)
    }

    private func persistBundlePolicies() {
        guard let data = try? JSONEncoder().encode(bundlePolicies) else { return }
        defaults.set(data, forKey: Key.bundlePolicies)
    }

    private func persistKnownItems() {
        guard let data = try? JSONEncoder().encode(knownItems) else { return }
        defaults.set(data, forKey: Key.knownItems)
    }

    private func persistWindowBindings() {
        guard let data = try? JSONEncoder().encode(windowBindings) else { return }
        defaults.set(data, forKey: Key.windowBindings)
    }

    private func persistAIItemDescriptions() {
        guard let data = try? JSONEncoder().encode(aiItemDescriptions) else { return }
        defaults.set(data, forKey: Key.aiItemDescriptions)
    }

    private static func isAnonymousStableID(_ stableID: String) -> Bool {
        stableID.hasPrefix("host:com.apple.controlcenter:")
            || stableID.hasPrefix("app:unknown.")
    }

    private static func isUsableBinding(_ binding: PersistedWindowBinding) -> Bool {
        !isAnonymousStableID(binding.stableID)
            && !(binding.semanticBundleIdentifier == "com.apple.controlcenter" && binding.semanticIdentifier.isEmpty)
            && !binding.semanticBundleIdentifier.hasPrefix("unknown.")
            && binding.displayName != "未识别的菜单栏图标"
            && binding.displayName != "Unrecognized menu bar item"
    }

    private static func sanitizedKnownItems(
        _ items: [String: KnownMenuBarItem]
    ) -> [String: KnownMenuBarItem] {
        let usable = items.filter { key, item in
            !isAnonymousStableID(key)
                && !item.semanticBundleIdentifier.isEmpty
                && !item.semanticBundleIdentifier.hasPrefix("unknown.")
                && item.displayName != "未识别的菜单栏图标"
                && item.displayName != "Unrecognized menu bar item"
                && !(PlatformVersion.isMacOS27OrNewer
                    && item.semanticBundleIdentifier.hasPrefix("com.apple."))
        }
        guard PlatformVersion.isMacOS27OrNewer else { return usable }

        var latestByBundle = [String: (key: String, item: KnownMenuBarItem)]()
        for (key, item) in usable {
            if latestByBundle[item.semanticBundleIdentifier].map({ $0.item.lastSeen < item.lastSeen }) ?? true {
                latestByBundle[item.semanticBundleIdentifier] = (key, item)
            }
        }
        return Dictionary(uniqueKeysWithValues: latestByBundle.values.map { ($0.key, $0.item) })
    }
}
